package com.utn.modelo;

public enum TipoTransporte {
	/*
	 * LOS ENUMERADORES SON UN TIPO DE OBJETO QUE GUARDAN O ALOJAN CONSTANTES
	 * LAS MISMAS SE DECLARAN EN MAYUSCULA Y SE SEPARAN POR COMA
	 * UN EJ LOS DIAS DE LA SEMANA
	 * 
	 * public enum diasSemana {
	 * DOMINGO,
	 * LUNES,
	 * MARTES,
	 * MIERCOLES,
	 * JUEVES,
	 * VIERNES,
	 * SAVADO
	 * }
	 * 
	 * ESTO QUIERE DECIR QUE NO EXISTE UN DIA DE LA SEMANA QUE NO ESTEMOS 
	 * CONTEMPLANDO Y TAMPOCO PODEMOS USAR
	 */
	
	TAXI,
	COLECTIVO
}
